// // https://env.t3.gg/docs/nextjs#create-your-schema
// import { createEnv } from '@t3-oss/env-nextjs'
// import { z } from 'zod'

// export const serverEnv = createEnv({
//   server: {
//     XAI_API_KEY: z.string().min(1),
//     OPENAI_API_KEY: z.string().min(1),
//     ANTHROPIC_API_KEY: z.string().min(1),
//     GROQ_API_KEY: z.string().min(1),
//     GOOGLE_GENERATIVE_AI_API_KEY: z.string().min(1),
//     DAYTONA_API_KEY: z.string().min(1),
//     DATABASE_URL: z.string().min(1),
//     BETTER_AUTH_SECRET: z.string().min(1),
//     GITHUB_CLIENT_ID: z.string().min(1),
//     GITHUB_CLIENT_SECRET: z.string().min(1),
//     GOOGLE_CLIENT_ID: z.string().min(1),
//     GOOGLE_CLIENT_SECRET: z.string().min(1),
//     TWITTER_CLIENT_ID: z.string().min(1),
//     TWITTER_CLIENT_SECRET: z.string().min(1),
//     REDIS_URL: z.string().min(1),
//     ELEVENLABS_API_KEY: z.string().min(1),
//     TAVILY_API_KEY: z.string().min(1),
//     EXA_API_KEY: z.string().min(1),
//     TMDB_API_KEY: z.string().min(1),
//     YT_ENDPOINT: z.string().min(1),
//     FIRECRAWL_API_KEY: z.string().min(1),
//     OPENWEATHER_API_KEY: z.string().min(1),
//     SANDBOX_TEMPLATE_ID: z.string().min(1),
//     GOOGLE_MAPS_API_KEY: z.string().min(1),
//     MAPBOX_ACCESS_TOKEN: z.string().min(1),
//     AMADEUS_API_KEY: z.string().min(1),
//     AMADEUS_API_SECRET: z.string().min(1),
//     CRON_SECRET: z.string().min(1),
//     BLOB_READ_WRITE_TOKEN: z.string().min(1),
//     MEM0_API_KEY: z.string().min(1),
//     MEM0_ORG_ID: z.string().min(1),
//     MEM0_PROJECT_ID: z.string().min(1),
//     SMITHERY_API_KEY: z.string().min(1),
//     COINGECKO_API_KEY: z.string().min(1),
//     ALLOWED_ORIGINS: z.string().optional().default('http://localhost:3000'),
//   },
//   experimental__runtimeEnv: process.env,
// })


// https://env.t3.gg/docs/nextjs#create-your-schema
import { createEnv } from '@t3-oss/env-nextjs'
import { z } from 'zod'

export const serverEnv = createEnv({
  server: {
    XAI_API_KEY: z.string().optional(),
    OPENAI_API_KEY: z.string().optional(),
    ANTHROPIC_API_KEY: z.string().optional(),
    GROQ_API_KEY: z.string().min(1),
    GOOGLE_GENERATIVE_AI_API_KEY: z.string().optional(),
    DEEPSEEK_API_KEY: z.string().optional(),
    DAYTONA_API_KEY: z.string().optional(),
    DATABASE_URL: z.string().optional(),
    BETTER_AUTH_SECRET: z.string().optional(),
    GITHUB_CLIENT_ID: z.string().optional(),
    GITHUB_CLIENT_SECRET: z.string().optional(),
    GOOGLE_CLIENT_ID: z.string().optional(),
    GOOGLE_CLIENT_SECRET: z.string().optional(),
    TWITTER_CLIENT_ID: z.string().optional(),
    TWITTER_CLIENT_SECRET: z.string().optional(),
    REDIS_URL: z.string().optional(),
    ELEVENLABS_API_KEY: z.string().optional(),
    TAVILY_API_KEY: z.string().optional(),
    EXA_API_KEY: z.string().optional(),
    TMDB_API_KEY: z.string().optional(),
    YT_ENDPOINT: z.string().optional(),
    FIRECRAWL_API_KEY: z.string().optional(),
    OPENWEATHER_API_KEY: z.string().optional(),
    SANDBOX_TEMPLATE_ID: z.string().optional(),
    GOOGLE_MAPS_API_KEY: z.string().optional(),
    MAPBOX_ACCESS_TOKEN: z.string().optional(),
    AMADEUS_API_KEY: z.string().optional(),
    AMADEUS_API_SECRET: z.string().optional(),
    CRON_SECRET: z.string().optional(),
    BLOB_READ_WRITE_TOKEN: z.string().optional(),
    MEM0_API_KEY: z.string().optional(),
    MEM0_ORG_ID: z.string().optional(),
    MEM0_PROJECT_ID: z.string().optional(),
    SMITHERY_API_KEY: z.string().optional(),
    COINGECKO_API_KEY: z.string().optional(),
    ALLOWED_ORIGINS: z.string().optional().default('http://localhost:3000'),
  },
  experimental__runtimeEnv: process.env,
})